title: "Codename: TEABAG"
description: "A friendly guide to escaping tutorial-hell"
show_downloads: true

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

markdown: CommonMarkGhPages
commonmark:
  options: ["UNSAFE", "SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
